version: '2'
services:
  shinobi:
    container_name: shinobi
    build:
      context: .
    restart: always
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_DATABASE=shinobi
      - MYSQL_USER=ccio
      - MYSQL_PASSWORD=shinobi
      - MYSQL_ROOT_PASSWORD=rootpass
## Timezone - eg Europe/London
      - TIMEZONE=UTC
    ports:
      - "8080:8080"
    volumes:
      - ./videos:/opt/shinobi/videos
      - ./dbdata:/var/lib/mysql
